### ISSUE TITLE
Bug: Squiggly lines on exported module names

### ISSUE THREAD

**Issue by EricForgy** [julia-vscode/julia-vscode#1140]
I am on Windows 10, Julia v1.3.1

I have a package with a bunch of nested submodules, i.e.

```julia
Package <- Sub1 <- Sub2 <- ... <- SubN
```
Each submodule exports all the submodules under it, e.g.

```julia
module Sub2

using Sub3

export Sub3, Sub4, ... , SubN
```

and

```julia
module Sub1

using Sub2

export Sub2, Sub3, ... , SubN
```

and

```julia
module Package

using Sub1

export Sub1, Sub2, ... , SubN
```

so that if I run

```julia
julia> using Package
```

in the REPL, I get all the submodules in my namespace and can do things like

```julia
julia> Sub1.stuff();
julia> Sub2.otherstuff()
```

Up until recently, syntax highlighting for this was working fine, but now I am getting squiggly lines under the exported submodule names.

I tried tracking it back to earlier versions because I know it was working before. I found that `0.5.18` and `0.5.19` work fine, but `0.5.23` introduced some change that broke this.

I hope this helps. I can run `0.5.19`, but this issue makes later versions unusuable to me 🙏

**Comment by EricForgy** [comment]
Here is a MWE:

### Folder structure:

```
MWE
|- Package
|- Sub1
|- Sub2
```

### Modules

```julia
module Sub2

otherstuff() = print("Other stuff")

end # module
```

```julia
module Sub1

using Sub2

export Sub2

stuff() = print("Stuff")

end # module
```

```julia
module Package

using Sub1

export Sub1, Sub2

end # module
```

### Project.toml

```toml
name = "Package"
uuid = "e05dae49-4c3c-4976-966c-df9ca5f5a3ae"
authors = ["Eric Forgy"]
version = "0.1.0"

[deps]
Sub1 = "bd4a7555-0f70-4691-8723-cd53f1a9457a"

```

### Manifest.toml

```toml
# This file is machine-generated - editing it directly is not advised

[[Sub1]]
deps = ["Sub2"]
path = "../Sub1"
uuid = "bd4a7555-0f70-4691-8723-cd53f1a9457a"
version = "0.1.0"

[[Sub2]]
path = "../Sub2"
uuid = "746ef646-937c-4279-9b97-9b9a1547a160"
version = "0.1.0"
```

Note the relative path in the Manifest ☝️ 

### Run the MWE

```julia
julia> using Package
[ Info: Precompiling Package [e05dae49-4c3c-4976-966c-df9ca5f5a3ae]

julia> Sub1.stuff()
Stuff
julia> Sub2.otherstuff()
Other stuff
julia>
```

### Screenshot

![image](https://user-images.githubusercontent.com/8954730/80209869-a75c3900-85e7-11ea-9b31-09262a736617.png)

There shouldn't be a squiggle on `Sub2` ☝️
