### ISSUE TITLE
Create Sysimage with execution_files

### ISSUE THREAD

**Issue by f-L0x** [julia-vscode/julia-vscode#2688]
I used a `` JuliaSysimage.toml `` with the following content

```toml
 [sysimage]
exclude = []  
statements_files = []
execution_files = ".vscode\\precompile.jl"
 ```

But this created an error in the `` task.compileenv.jl ``
```julia
ERROR: LoadError: MethodError: no method matching joinpath(::String, ::Char)
 ```

I think a solution could be a additional `` String[ ... ]`` inside the for loop in line 55 & 56

```julia
    output[:precompile_execution_file] = String[joinpath(envdir, x) for x in String[get(parsed, "execution_files", String[])]]
    output[:precompile_statements_file] = String[joinpath(envdir, x) for x in String[get(parsed, "statements_files", String[])]]
 ```

This worked for me but I didn't checked this with other possible `` JuliaSysimage.toml `` files
