### ISSUE TITLE
Test process crashes on running @testitem with "ERROR: can not merge projects"

### ISSUE THREAD

**Issue by DaniGlez** [julia-vscode/julia-vscode#3104]
On v1.31.1 pre-release, any `@testitem` run in my private package results in a test process crash with the following output:

```julia
  Activating new project at `/tmp/jl_HJHS9z`
   Resolving package versions...
    Updating `/tmp/jl_HJHS9z/Project.toml`
  [b350████] + ████ v0.2.1 `~/projects/█████`
    Updating `/tmp/jl_HJHS9z/Manifest.toml`
  [a4c015fc] + ANSIColoredPrinters v0.0.1
  [ac637c84] + AbbreviatedStackTraces v0.1.4
  [c3fe647b] + AbstractAlgebra v0.27.5
  [621f4979] + AbstractFFTs v1.2.1
  [1520ce14] + AbstractTrees v0.4.2
  [7d9f7c33] + Accessors v0.1.20
  [79e6a3ab] + Adapt v3.4.0
  [dce04be8] + ArgCheck v2.3.0
  [ec485272] + ArnoldiMethod v0.2.0
  [4fba245c] + ArrayInterface v6.0.23
  [30b0a656] + ArrayInterfaceCore v0.1.20
  [6ba088a2] + ArrayInterfaceGPUArrays v0.2.2
  [015c0d05] + ArrayInterfaceOffsetArrays v0.1.6
  [b0d46f97] + ArrayInterfaceStaticArrays v0.1.4
  [dd5226c6] + ArrayInterfaceStaticArraysCore v0.1.0
  [a2b0951a] + ArrayInterfaceTracker v0.1.1
  [4c555306] + ArrayLayouts v0.8.11
  [bf4720bc] + AssetRegistry v0.1.0
  [a9b6321e] + Atomix v0.1.0
  [15f4f7f2] + AutoHashEquals v0.2.0
  [e7028de2] + AutoPreallocation v0.3.1
  [13072b0f] + AxisAlgorithms v1.0.1
⌅ [ab4f0b2a] + BFloat16s v0.2.0
  [aae01518] + BandedMatrices v0.17.7
  [198e06fe] + BangBang v0.3.37
  [9718e550] + Baselet v0.1.1
  [6e4b80f9] + BenchmarkTools v1.3.1
  [e2ed5e7c] + Bijections v0.1.4
  [9e28174c] + BinDeps v1.0.2
  [62783981] + BitTwiddlingConvenienceFunctions v0.1.4
  [ad839575] + Blink v0.12.5
  [764a87c0] + BoundaryValueDiffEq v2.9.0
  [fa961155] + CEnum v0.4.2
  [2a0fbf3d] + CPUSummary v0.1.27
  [00ebfdb7] + CSTParser v3.3.6
  [052768ef] + CUDA v3.12.0
  [72cfdca4] + CUDAKernels v0.4.3
  [159f3aea] + Cairo v1.0.5
  [49dc2e85] + Calculus v0.5.1
  [7057c7e9] + Cassette v0.3.10
  [082447d4] + ChainRules v1.44.6
  [d360d2e6] + ChainRulesCore v1.15.6
  [9e997f8a] + ChangesOfVariables v0.1.4
  [fb6a15b2] + CloseOpenIntervals v0.1.10
  [da1fd8a2] + CodeTracking v1.1.0
  [523fee87] + CodecBzip2 v0.7.2
  [944b1d66] + CodecZlib v0.7.0
  [35d6a980] + ColorSchemes v3.19.0
  [3da002f7] + ColorTypes v0.11.4
  [c3611d14] + ColorVectorSpace v0.9.9
  [5ae59095] + Colors v0.12.8
  [861a8166] + Combinatorics v1.0.2
  [a80b9123] + CommonMark v0.8.6
  [38540f10] + CommonSolve v0.2.1
  [bbf7d656] + CommonSubexpressions v0.3.0
  [34da2185] + Compat v4.3.0
  [b0b7db55] + ComponentArrays v0.13.3
  [b152e2b5] + CompositeTypes v0.1.2
  [a33af91c] + CompositionsBase v0.1.1
  [8f4d0f93] + Conda v1.7.0
  [88cd18e8] + ConsoleProgressMonitor v0.1.2
  [187b0558] + ConstructionBase v1.4.1
  [6add18c4] + ContextVariablesX v0.1.3
  [d38c429a] + Contour v0.6.2
  [a2441757] + Coverage v1.6.0
  [c36e975a] + CoverageTools v1.3.0
  [adafc99b] + CpuId v0.3.1
  [a8cc5b0e] + Crayons v4.1.1
  [9a962f9c] + DataAPI v1.12.0
  [82cc6244] + DataInterpolations v3.10.1
  [864edb3b] + DataStructures v0.18.13
  [e2d170a0] + DataValueInterfaces v1.0.0
  [244e2a9f] + DefineSingletons v0.1.2
  [bcd4f6db] + DelayDiffEq v5.38.0
  [b429d917] + DensityInterface v0.4.0
  [2b5f629d] + DiffEqBase v6.105.1
  [459566f4] + DiffEqCallbacks v2.24.1
  [aae7a2af] + DiffEqFlux v1.52.0
  [77a26b50] + DiffEqNoiseProcess v5.13.0
  [163ba53b] + DiffResults v1.1.0
  [b552c78f] + DiffRules v1.11.1
  [0c46a032] + DifferentialEquations v7.5.0
  [b4f34e82] + Distances v0.10.7
  [31c24e10] + Distributions v0.25.75
  [ced4e74d] + DistributionsAD v0.6.43
  [ffbed154] + DocStringExtensions v0.9.1
  [e30172f5] + Documenter v0.27.23
  [5b8099bc] + DomainSets v0.5.13
  [fa6b7ba4] + DualNumbers v0.6.8
  [7c1d4256] + DynamicPolynomials v0.4.5
  [da5c29d0] + EllipsisNotation v1.6.0
  [7da242da] + Enzyme v0.10.8
  [d4d017d3] + ExponentialUtilities v1.19.0
  [e2ba6199] + ExprTools v0.1.8
  [c87230d0] + FFMPEG v0.4.1
  [cc61a311] + FLoops v0.2.1
  [b9860ae5] + FLoopsBase v0.1.1
  [7034ab61] + FastBroadcast v0.2.1
  [9aa1b823] + FastClosures v0.3.2
  [29a986be] + FastLapackInterface v1.2.7
  [5789e2e9] + FileIO v1.15.0
  [1a297f60] + FillArrays v0.13.4
  [6a86dc24] + FiniteDiff v2.15.0
  [53c48c17] + FixedPointNumbers v0.8.4
  [08572546] + FlameGraphs v1.0.0
  [587475ba] + Flux v0.13.6
  [9c68100b] + FoldsThreads v0.1.1
  [59287772] + Formatting v0.4.2
  [f6369f11] + ForwardDiff v0.10.32
  [069b7b12] + FunctionWrappers v1.1.3
  [77dc65aa] + FunctionWrappersWrappers v0.1.1
  [de31a74c] + FunctionalCollections v0.5.0
  [d9f16b24] + Functors v0.3.0
  [0c68f7d7] + GPUArrays v8.5.0
  [46192b85] + GPUArraysCore v0.1.2
  [61eb1bfa] + GPUCompiler v0.16.4
  [28b8d3ca] + GR v0.69.4
  [6b9d7cbe] + GeneralizedGenerated v0.3.3
  [c145ed77] + GenericSchur v0.5.3
  [a2bd30eb] + Graphics v1.1.2
  [86223c79] + Graphs v1.7.4
  [42e2da0e] + Grisu v1.0.2
  [0b43b601] + Groebner v0.2.10
  [d5909c97] + GroupsCore v0.4.0
  [4c0ca9eb] + Gtk v1.2.2
  [8710efd8] + GtkObservables v1.2.5
⌅ [cd3eb016] + HTTP v0.9.17
  [9fb69e20] + Hiccup v0.2.2
  [3e5b6fbb] + HostCPUFeatures v0.1.8
  [34004b35] + HypergeometricFunctions v0.3.11
  [b5f81e59] + IOCapture v0.2.2
  [7869d1d1] + IRTools v0.4.6
  [615f187c] + IfElse v0.1.1
  [9b13fd28] + IndirectArrays v1.0.0
  [d25df0c9] + Inflate v0.1.3
  [83e8ac13] + IniFile v0.5.1
  [22cec73e] + InitialValues v0.3.1
  [18e54dd8] + IntegerMathUtils v0.1.0
⌅ [a98d9a8b] + Interpolations v0.13.6
  [8197267c] + IntervalSets v0.7.3
  [3587e190] + InverseFunctions v0.1.8
  [92d709cd] + IrrationalConstants v0.1.1
  [42fd0dbc] + IterativeSolvers v0.9.2
  [82899510] + IteratorInterfaceExtensions v1.0.0
  [1019f520] + JLFzf v0.1.5
  [692b3bcd] + JLLWrappers v1.4.1
  [97c1335a] + JSExpr v0.5.4
  [682c06a0] + JSON v0.21.3
  [b9b8584e] + JSONRPC v1.3.4
  [4076af6c] + JuMP v1.3.1
  [98e50ef6] + JuliaFormatter v1.0.10
  [aa1ae85d] + JuliaInterpreter v0.9.15
  [b14d175d] + JuliaVariables v0.2.4
  [ccbc3e58] + JumpProcesses v9.2.0
⌅ [ef3ab10e] + KLU v0.3.0
  [63c18a36] + KernelAbstractions v0.8.4
  [ba0b0d4f] + Krylov v0.8.4
  [0b1a1467] + KrylovKit v0.5.4
  [929cbde3] + LLVM v4.14.0
  [b964fa9f] + LaTeXStrings v1.3.0
  [2ee39098] + LabelledArrays v1.12.0
  [984bce1d] + LambertW v0.4.5
  [2b0e0bc5] + LanguageServer v4.3.1
  [23fbe1c1] + Latexify v0.15.17
  [10f19ff3] + LayoutPointers v0.1.10
  [50d2b5c4] + Lazy v0.15.1
  [0fc2ff8b] + LeastSquaresOptim v0.8.3
  [1d6d02ad] + LeftChildRightSiblingTrees v0.2.0
  [2d8b4e74] + LevyArea v1.0.0
  [d3d80556] + LineSearches v7.2.0
  [7ed4a6bd] + LinearSolve v1.26.1
  [89398ba2] + LocalRegistry v0.5.2
  [2ab3a3ac] + LogExpFunctions v0.3.18
  [e6f89c97] + LoggingExtras v0.4.9
  [bdcacae8] + LoopVectorization v0.12.132
  [6f1432cf] + LoweredCodeUtils v2.2.2
  [b2108857] + Lux v0.4.27
  [82251201] + LuxLib v0.1.6
  [d8e11817] + MLStyle v0.4.14
  [f1d291b0] + MLUtils v0.2.11
  [1914dd2f] + MacroTools v0.5.10
  [d125e4d3] + ManualMemory v0.1.8
  [b8f27783] + MathOptInterface v1.8.2
  [739be429] + MbedTLS v1.1.6
  [442fdcdd] + Measures v0.3.1
  [c03570c3] + Memoize v0.4.4
  [e9d8d322] + Metatheory v1.3.5
  [85b6ec6f] + MethodAnalysis v0.4.10
  [128add7d] + MicroCollections v0.1.3
  [e1d29d7a] + Missings v1.0.2
  [961ee093] + ModelingToolkit v8.26.1
  [46d2c3a1] + MuladdMacro v0.2.2
  [102ac46a] + MultivariatePolynomials v0.4.6
  [ffc61752] + Mustache v1.0.14
  [d8a4904e] + MutableArithmetics v1.0.4
⌅ [a975b10e] + Mux v0.7.6
  [d41bc354] + NLSolversBase v7.8.2
  [2774e3e8] + NLsolve v4.5.1
  [872c559c] + NNlib v0.8.9
  [a00861dc] + NNlibCUDA v0.2.4
  [77ba4419] + NaNMath v1.0.1
  [71a1bf82] + NameResolution v0.1.5
  [8913a72c] + NonlinearSolve v0.3.22
  [d8793406] + ObjectFile v0.3.7
  [510215fc] + Observables v0.5.2
  [6fe1bfb0] + OffsetArrays v1.12.7
  [0b1bfda6] + OneHotArrays v0.1.0
  [429524aa] + Optim v1.7.3
  [3bd65402] + Optimisers v0.2.9
  [7f7a1694] + Optimization v3.9.0
  [253f991c] + OptimizationFlux v0.1.0
  [36348300] + OptimizationOptimJL v0.1.2
  [42dfb2eb] + OptimizationOptimisers v0.1.0
  [500b13db] + OptimizationPolyalgorithms v0.1.0
  [fbd9d27c] + OptionalData v1.0.0
  [bac558e1] + OrderedCollections v1.4.1
  [1dea7af3] + OrdinaryDiffEq v6.28.0
  [90014a1f] + PDMats v0.11.16
⌅ [9b87118b] + PackageCompiler v1.6.0
  [d96e819e] + Parameters v0.12.3
  [69de0a69] + Parsers v2.4.0
  [fa939f87] + Pidfile v1.3.0
  [b98c9c47] + Pipe v1.3.0
  [ccf2f8ad] + PlotThemes v3.0.0
  [995b91a9] + PlotUtils v1.3.1
  [58dd65bb] + Plotly v0.4.1
  [a03496cd] + PlotlyBase v0.8.19
  [f0f68f2c] + PlotlyJS v0.18.10
  [91a5bcdd] + Plots v1.35.2
  [e409e4f3] + PoissonRandom v0.4.1
  [f517fe37] + Polyester v0.6.16
  [1d0040c9] + PolyesterWeave v0.1.10
  [3a141323] + PolynomialRoots v1.0.0
  [85a6dd25] + PositiveFactorizations v0.2.4
  [d236fae5] + PreallocationTools v0.4.4
  [21216c6a] + Preferences v1.3.0
  [8162dcfd] + PrettyPrint v0.2.0
⌅ [08abe8d2] + PrettyTables v1.3.1
  [27ebfcd6] + Primes v0.5.3
  [c46f51b8] + ProfileView v1.5.2
  [33c8b6b6] + ProgressLogging v0.1.4
  [92933f4c] + ProgressMeter v1.7.2
  [438e738f] + PyCall v1.94.1
  [d330b81b] + PyPlot v2.11.0
  [1fd47b50] + QuadGK v2.5.0
  [94ee1d12] + Quaternions v0.5.7
  [74087812] + Random123 v1.6.0
  [fb686558] + RandomExtensions v0.4.3
  [e6cf234a] + RandomNumbers v1.5.3
  [c84ed2f1] + Ratios v0.4.3
  [c1ae055f] + RealDot v0.1.0
  [3cdcf5f2] + RecipesBase v1.3.0
  [01d81517] + RecipesPipeline v0.6.6
  [731186ca] + RecursiveArrayTools v2.32.0
  [f2c3362d] + RecursiveFactorization v0.2.12
  [189a3867] + Reexport v1.2.2
⌅ [74f56ac7] + ReferenceFrameRotations v1.0.1
  [42d2dcc6] + Referenceables v0.1.2
  [d1eb7eb1] + RegistryTools v1.8.1
  [29dad682] + RegularizationTools v0.6.0
  [05181044] + RelocatableFolders v1.0.0
⌅ [cbe49d4c] + RemoteFiles v0.4.2
  [ae029012] + Requires v1.3.0
  [ae5879a3] + ResettableStacks v1.1.1
  [37e2e3b7] + ReverseDiff v1.14.3
  [295af30f] + Revise v3.4.0
  [79098fc4] + Rmath v0.7.0
  [6038ab10] + Rotations v1.3.2
  [d5f540fe] + RoundingIntegers v1.1.0
  [7e49a35a] + RuntimeGeneratedFunctions v0.5.3
  [3cdde19b] + SIMDDualNumbers v0.1.1
  [94e857df] + SIMDTypes v0.1.0
  [476501e8] + SLEEFPirates v0.6.36
  [6ac157d9] + SatelliteToolbox v0.9.4
  [0bca4576] + SciMLBase v1.59.4
  [1ed8b502] + SciMLSensitivity v7.10.0
  [6c6a2e73] + Scratch v1.1.1
  [efcf1570] + Setfield v1.1.1
  [605ecd9f] + ShowCases v0.1.0
  [992d4aef] + Showoff v1.0.3
  [b8d349fb] + SimpleContainerGenerator v2.0.2
  [699a6c99] + SimpleTraits v0.9.4
  [47aef6b3] + SimpleWeightedGraphs v1.2.1
  [66db9d55] + SnoopPrecompile v1.0.1
  [a2af1166] + SortingAlgorithms v1.0.1
  [47a9eef4] + SparseDiffTools v1.26.2
  [276daf66] + SpecialFunctions v2.1.7
  [171d559e] + SplittablesBase v0.1.15
  [aedffcd0] + Static v0.7.7
  [90137ffa] + StaticArrays v1.5.9
  [1e83bf80] + StaticArraysCore v1.4.0
  [b3cc710f] + StaticLint v8.1.0
  [82ae8749] + StatsAPI v1.5.0
  [2913bbd2] + StatsBase v0.33.21
  [4c63d2b9] + StatsFuns v1.0.1
  [9672c7b4] + SteadyStateDiffEq v1.9.0
  [789caeaf] + StochasticDiffEq v6.54.0
  [7792a7ef] + StrideArraysCore v0.3.15
  [09ab397b] + StructArrays v0.6.12
  [53d494c1] + StructIO v0.3.0
  [c3572dad] + Sundials v4.10.1
  [cf896787] + SymbolServer v7.2.1
  [d1185830] + SymbolicUtils v0.19.11
  [0c5d862f] + Symbolics v4.11.0
  [3783bdb8] + TableTraits v1.0.1
  [bd369af6] + Tables v1.9.0
  [62fd8b95] + TensorCore v0.1.1
⌅ [8ea1fca8] + TermInterface v0.2.3
  [5d786b92] + TerminalLoggers v0.1.6
  [1c621080] + TestItems v0.1.0
  [8290d209] + ThreadingUtilities v0.5.0
  [ac1d9e8a] + ThreadsX v0.1.11
  [a759f4b9] + TimerOutputs v0.5.21
  [0796e94c] + Tokenize v0.5.24
  [9f7883ad] + Tracker v0.2.22
  [3bb67fe8] + TranscodingStreams v0.9.9
  [28d57a85] + Transducers v0.4.74
  [a2a6695c] + TreeViews v0.3.0
  [d5829a12] + TriangularSolve v0.1.14
  [410a4b4d] + Tricks v0.1.6
  [30578b45] + URIParser v0.4.1
  [5c2747f8] + URIs v1.4.0
  [3a884ed6] + UnPack v1.0.2
  [d9a01c3f] + Underscores v3.0.0
  [1cfade01] + UnicodeFun v0.4.1
  [1986cc42] + Unitful v1.12.0
  [013be700] + UnsafeAtomics v0.2.1
  [d80eeb9a] + UnsafeAtomicsLLVM v0.1.0
  [41fe7b60] + Unzip v0.2.0
  [0625e100] + ValSplit v0.1.0
  [3d5dd08c] + VectorizationBase v0.21.51
  [81def892] + VersionParsing v1.3.0
  [19fa3120] + VertexSafeGraphs v0.2.0
  [0f1e0344] + WebIO v0.8.18
  [104b5d7c] + WebSockets v1.5.9
  [cc8bc4a8] + Widgets v0.6.6
  [efce3f68] + WoodburyMatrices v0.5.5
  [e88e6eb3] + Zygote v0.6.49
  [700de1a5] + ZygoteRules v0.2.2
  [b3500434] + i360 v0.2.1 `~/projects/i360-jl`
  [7b86fcea] + ATK_jll v2.36.1+0
  [6e34b625] + Bzip2_jll v1.0.8+0
  [83423d85] + Cairo_jll v1.16.1+1
  [ee1fde0b] + Dbus_jll v1.12.16+3
  [7cc45869] + Enzyme_jll v0.0.41+0
  [2e619515] + Expat_jll v2.4.8+0
  [b22a6f82] + FFMPEG_jll v4.4.2+2
  [a3f928ae] + Fontconfig_jll v2.13.93+0
  [d7e528f0] + FreeType2_jll v2.10.4+0
  [559328eb] + FriBidi_jll v1.0.10+0
  [0656b61e] + GLFW_jll v3.3.8+0
  [d2c73de3] + GR_jll v0.69.1+0
  [77ec8976] + GTK3_jll v3.24.31+0
  [78b55507] + Gettext_jll v0.21.0+0
  [7746bdde] + Glib_jll v2.74.0+1
  [3b182d85] + Graphite2_jll v1.3.14+0
  [2e76f6c2] + HarfBuzz_jll v2.8.1+1
  [aacddb02] + JpegTurbo_jll v2.1.2+0
  [f7e6163d] + Kaleido_jll v0.2.1+0
  [c1c5ebd0] + LAME_jll v3.100.1+0
  [88015f11] + LERC_jll v3.0.0+1
  [dad2f222] + LLVMExtra_jll v0.0.16+0
  [dd4b983a] + LZO_jll v2.10.1+0
  [42c93a91] + Libepoxy_jll v1.5.8+1
  [e9f186c6] + Libffi_jll v3.2.2+1
  [d4300ac3] + Libgcrypt_jll v1.8.7+0
  [7e76a0d4] + Libglvnd_jll v1.3.0+3
  [7add5ba3] + Libgpg_error_jll v1.42.0+0
  [94ce4f54] + Libiconv_jll v1.16.1+1
  [4b2f31a3] + Libmount_jll v2.35.0+0
  [925c91fb] + Librsvg_jll v2.52.4+0
  [89763e89] + Libtiff_jll v4.4.0+0
  [38a345b3] + Libuuid_jll v2.36.0+0
  [e7412a2a] + Ogg_jll v1.3.5+1
  [458c3c95] + OpenSSL_jll v1.1.17+0
  [efe28fd5] + OpenSpecFun_jll v0.5.5+0
  [91d4177d] + Opus_jll v1.3.2+0
  [36c8627f] + Pango_jll v1.50.9+0
  [30392449] + Pixman_jll v0.40.1+0
  [ea2cea3b] + Qt5Base_jll v5.15.3+1
  [f50d1b31] + Rmath_jll v0.3.0+0
  [fb77eaff] + Sundials_jll v5.2.1+0
  [a2964d1f] + Wayland_jll v1.19.0+0
  [2381bf8a] + Wayland_protocols_jll v1.25.0+0
  [02c8fc9c] + XML2_jll v2.9.14+0
  [aed1982a] + XSLT_jll v1.1.34+0
  [4f6342f7] + Xorg_libX11_jll v1.6.9+4
  [0c0b7dd1] + Xorg_libXau_jll v1.0.9+4
  [3c9796d7] + Xorg_libXcomposite_jll v0.4.5+4
  [935fb764] + Xorg_libXcursor_jll v1.2.0+4
  [0aeada51] + Xorg_libXdamage_jll v1.1.5+4
  [a3789734] + Xorg_libXdmcp_jll v1.1.3+4
  [1082639a] + Xorg_libXext_jll v1.3.4+4
  [d091e8ba] + Xorg_libXfixes_jll v5.0.3+4
  [a51aa0fd] + Xorg_libXi_jll v1.7.10+4
  [d1454406] + Xorg_libXinerama_jll v1.1.4+4
  [ec84b674] + Xorg_libXrandr_jll v1.5.2+4
  [ea2f1a96] + Xorg_libXrender_jll v0.9.10+4
  [b6f176f1] + Xorg_libXtst_jll v1.2.3+4
  [14d82f49] + Xorg_libpthread_stubs_jll v0.1.0+3
  [c7cfdc94] + Xorg_libxcb_jll v1.13.0+3
  [cc61e674] + Xorg_libxkbfile_jll v1.1.0+4
  [12413925] + Xorg_xcb_util_image_jll v0.4.0+1
  [2def613f] + Xorg_xcb_util_jll v0.4.0+1
  [975044d2] + Xorg_xcb_util_keysyms_jll v0.4.0+1
  [0d47668e] + Xorg_xcb_util_renderutil_jll v0.3.9+1
  [c22f9ab0] + Xorg_xcb_util_wm_jll v0.4.1+1
  [35661453] + Xorg_xkbcomp_jll v1.4.2+4
  [33bec58e] + Xorg_xkeyboard_config_jll v2.27.0+4
  [c5fb5394] + Xorg_xtrans_jll v1.4.0+3
  [3161d3a3] + Zstd_jll v1.5.2+0
  [b437f822] + adwaita_icon_theme_jll v3.33.92+5
  [de012916] + at_spi2_atk_jll v2.34.1+4
  [0fc3237b] + at_spi2_core_jll v2.34.0+4
⌅ [214eeab7] + fzf_jll v0.29.0+0
  [da03df04] + gdk_pixbuf_jll v2.42.8+0
  [059c91fe] + hicolor_icon_theme_jll v0.17.0+3
  [bf975903] + iso_codes_jll v4.11.0+0
  [a4ae2306] + libaom_jll v3.4.0+0
  [0ac62f75] + libass_jll v0.15.1+0
  [f638f0a6] + libfdk_aac_jll v2.0.2+0
  [b53b4c65] + libpng_jll v1.6.38+0
  [f27f6e37] + libvorbis_jll v1.3.7+1
  [1270edf5] + x264_jll v2021.5.5+0
  [dfaa095f] + x265_jll v3.5.0+0
  [d8fb68d0] + xkbcommon_jll v1.4.1+0
  [0dad84c5] + ArgTools v1.1.1
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8bb1440f] + DelimitedFiles
  [8ba89e20] + Distributed
  [f43a241f] + Downloads v1.6.0
  [7b1f6079] + FileWatching
  [9fa8497b] + Future
  [b77e0a4c] + InteractiveUtils
  [4af54fe1] + LazyArtifacts
  [b27032c2] + LibCURL v0.6.3
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [ca575930] + NetworkOptions v1.2.0
  [44cfe95a] + Pkg v1.8.0
  [de0858da] + Printf
  [9abbd945] + Profile
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA v0.7.0
  [9e88b42a] + Serialization
  [1a1011a3] + SharedArrays
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [4607b0f0] + SuiteSparse
  [fa267f1f] + TOML v1.0.0
  [a4e569a6] + Tar v1.10.1
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [e66e0078] + CompilerSupportLibraries_jll v0.5.2+0
  [deac9b47] + LibCURL_jll v7.84.0+0
  [29816b5a] + LibSSH2_jll v1.10.2+0
  [c8ffd9c3] + MbedTLS_jll v2.28.0+0
  [14a3606d] + MozillaCACerts_jll v2022.2.1
  [4536629a] + OpenBLAS_jll v0.3.20+0
  [05823500] + OpenLibm_jll v0.8.1+0
  [efcefdf7] + PCRE2_jll v10.40.0+0
  [bea87d4a] + SuiteSparse_jll v5.10.1+0
  [83775a58] + Zlib_jll v1.2.12+3
  [8e850b90] + libblastrampoline_jll v5.1.1+0
  [8e850ede] + nghttp2_jll v1.48.0+0
  [3f19e933] + p7zip_jll v17.4.0+0
        Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`
┌ Error: Some Julia code in the VS Code extension crashed
└ @ Main ~/.vscode/extensions/julialang.language-julia-1.31.1/scripts/error_handler.jl:15
ERROR: can not merge projects
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types ~/apps/julia-1.8.2/share/julia/stdlib/v1.8/Pkg/src/Types.jl:67
  [2] (::Pkg.Operations.var"#105#110"{Nothing, Bool, Bool, Bool, VSCodeTestServer.TestEnv.var"#2#3"{VSCodeTestServer.var"#13#15"{Base.PipeEndpoint}}, Pkg.Types.Context, Pkg.Types.PackageSpec, String, Nothing, String})(tmp::String)
    @ Pkg.Operations ~/apps/julia-1.8.2/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1566
  [3] mktempdir(fn::Pkg.Operations.var"#105#110"{Nothing, Bool, Bool, Bool, VSCodeTestServer.TestEnv.var"#2#3"{VSCodeTestServer.var"#13#15"{Base.PipeEndpoint}}, Pkg.Types.Context, Pkg.Types.PackageSpec, String, Nothing, String}, parent::String; prefix::String)
    @ Base.Filesystem ./file.jl:764
  [4] mktempdir(fn::Function, parent::String) (repeats 2 times)
    @ Base.Filesystem ./file.jl:760
  [5] sandbox(fn::Function, ctx::Pkg.Types.Context, target::Pkg.Types.PackageSpec, target_path::String, sandbox_path::String, sandbox_project_override::Nothing; preferences::Nothing, force_latest_compatible_version::Bool, allow_earlier_backwards_compatible_versions::Bool, allow_reresolve::Bool)
    @ Pkg.Operations ~/apps/julia-1.8.2/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1540
  [6] sandbox
    @ ~/apps/julia-1.8.2/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1531 [inlined]
  [7] activate(f::VSCodeTestServer.var"#13#15"{Base.PipeEndpoint}, pkg::String)
    @ VSCodeTestServer.TestEnv ~/.vscode/extensions/julialang.language-julia-1.31.1/scripts/packages/TestEnv/src/julia-1.8/activate_do.jl:16
  [8] serve(conn::Base.PipeEndpoint, project_path::String, package_path::String, package_name::String; is_dev::Bool, crashreporting_pipename::Nothing)
    @ VSCodeTestServer ~/.vscode/extensions/julialang.language-julia-1.31.1/scripts/packages/VSCodeTestServer/src/VSCodeTestServer.jl:196
  [9] serve(conn::Base.PipeEndpoint, project_path::String, package_path::String, package_name::String)
    @ VSCodeTestServer ~/.vscode/extensions/julialang.language-julia-1.31.1/scripts/packages/VSCodeTestServer/src/VSCodeTestServer.jl:190
 [10] top-level scope
    @ ~/.vscode/extensions/julialang.language-julia-1.31.1/scripts/testserver/testserver_main.jl:14
 [11] include(mod::Module, _path::String)
    @ Base ./Base.jl:419
 [12] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:303
 [13] _start()
    @ Base ./client.jl:522


> Test run finished at 10/7/2022, 11:11:46 AM <
```

The Project.toml reads as follows:

```toml
name = "██████"
uuid = "b350████████████████"
authors = ["████████████████"]
version = "0.2.1"

[deps]
AbbreviatedStackTraces = "ac637c84-cc71-43bf-9c33-c1b4316be3d4"
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
AutoPreallocation = "e7028de2-df94-4053-9fdc-99272086b8d4"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DiffEqFlux = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FLoops = "cc61a311-1640-44b5-9fba-1b764f453329"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LocalRegistry = "89398ba2-070a-4b16-a995-9893c55d93cf"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Plotly = "58dd65bb-95f3-509e-9936-c39a10fdeae7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Quaternions = "94ee1d12-ae83-5a48-8b1c-48b8ff168ae0"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SatelliteToolbox = "6ac157d9-b43d-51bb-8fab-48bf53814f4a"
SimpleContainerGenerator = "b8d349fb-717b-4aac-a9b1-e1da4219c631"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
ValSplit = "0625e100-946b-11ec-09cd-6328dd093154"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1.8"

[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
```
